name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Check for console.log statements
      run: |
        if grep -r "console\.log" src/; then
          echo "Warning: console.log statements found in source code"
          exit 1
        fi
        
    - name: Check for TODO/FIXME comments
      run: |
        if grep -r "TODO\|FIXME" src/; then
          echo "Warning: TODO/FIXME comments found in source code"
          exit 1
        fi 